import { Course } from '@/types';

// Seed data for courses when database is not connected
export const SEED_COURSES: Course[] = [
  // Cambridge English Programs
  {
    id: '1',
    title: 'English Level 1 - The Pioneer',
    category: 'Cambridge English Programs',
    age_range: '4-5',
    description: 'Foundation English program for young learners. Build essential language skills through interactive activities, songs, and stories.',
    schedule: 'Sat & Sun, 9:00 AM - 10:30 AM',
    duration: '6 months',
    fee: 2500,
    subjects: ['Phonics', 'Basic Vocabulary', 'Listening Skills', 'Speaking Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'English Level 2 - The Achiever',
    category: 'Cambridge English Programs',
    age_range: '6-7',
    description: 'Develop reading and writing skills while expanding vocabulary. Perfect for early primary students.',
    schedule: 'Sat & Sun, 11:00 AM - 12:30 PM',
    duration: '6 months',
    fee: 2800,
    subjects: ['Reading Comprehension', 'Writing Basics', 'Grammar Introduction', 'Vocabulary Building'],
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'English Level 3 - The Scholar',
    category: 'Cambridge English Programs',
    age_range: '8-9',
    description: 'Intermediate English focusing on comprehensive language skills and academic preparation.',
    schedule: 'Sat & Sun, 2:00 PM - 3:30 PM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Advanced Reading', 'Essay Writing', 'Grammar Mastery', 'Public Speaking'],
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'English Level 4 - The Titleholder',
    category: 'Cambridge English Programs',
    age_range: '10-12',
    description: 'Advanced English program preparing students for secondary education and Cambridge examinations.',
    schedule: 'Sat & Sun, 4:00 PM - 5:30 PM',
    duration: '6 months',
    fee: 3500,
    subjects: ['Critical Reading', 'Academic Writing', 'Advanced Grammar', 'Debate Skills'],
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'English Level 5 - The Leader',
    category: 'Cambridge English Programs',
    age_range: '13-16',
    description: 'Comprehensive O-Level preparation program with focus on examination techniques and advanced language skills.',
    schedule: 'Sat & Sun, 6:00 PM - 7:30 PM',
    duration: '6 months',
    fee: 4000,
    subjects: ['O-Level English', 'Literature Analysis', 'Advanced Composition', 'Exam Preparation'],
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'O-Level English Exam Preparation',
    category: 'Cambridge English Programs',
    age_range: '10-16',
    description: 'Intensive exam preparation course focusing on O-Level English examination requirements and techniques.',
    schedule: 'Fri 4:00 PM - 6:00 PM, Sat 10:00 AM - 12:00 PM',
    duration: '4 months',
    fee: 4500,
    subjects: ['Paper 1 Preparation', 'Paper 2 Preparation', 'Past Paper Practice', 'Exam Techniques'],
    created_at: new Date().toISOString(),
  },
  
  // Enrichment Programs
  {
    id: '7',
    title: 'Level-3 Scholar Enrichment',
    category: 'Enrichment Programs',
    age_range: '6-9',
    description: 'Multi-subject enrichment program combining English, Maths, Science, and Art for holistic development.',
    schedule: 'Sat & Sun, 9:00 AM - 12:00 PM',
    duration: '6 months',
    fee: 5000,
    subjects: ['English', 'Maths', 'Science', 'Art'],
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Level-4 Titleholder Enrichment',
    category: 'Enrichment Programs',
    age_range: '10-12',
    description: 'Comprehensive enrichment covering core subjects plus business studies for well-rounded education.',
    schedule: 'Sat & Sun, 2:00 PM - 5:00 PM',
    duration: '6 months',
    fee: 5500,
    subjects: ['English', 'Maths', 'Combined Science', 'Business Studies'],
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'Level-5 Leader Enrichment',
    category: 'Enrichment Programs',
    age_range: '13-14',
    description: 'Advanced enrichment program preparing students for O-Level success across multiple subjects.',
    schedule: 'Sat & Sun, 5:00 PM - 8:00 PM',
    duration: '6 months',
    fee: 6000,
    subjects: ['English', 'Maths', 'Combined Science', 'Business Studies'],
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'O-Level Prep - Commerce Stream',
    category: 'Enrichment Programs',
    age_range: '14-16',
    description: 'Complete O-Level preparation for commerce stream students with focus on business subjects.',
    schedule: 'Fri 3:00 PM - 8:00 PM, Sat 3:00 PM - 8:00 PM',
    duration: '8 months',
    fee: 8000,
    subjects: ['English', 'Maths', 'Accounts', 'Business Studies', 'Economics'],
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    title: 'O-Level Prep - Science Stream',
    category: 'Enrichment Programs',
    age_range: '14-16',
    description: 'Complete O-Level preparation for science stream students with focus on science subjects.',
    schedule: 'Fri 3:00 PM - 8:00 PM, Sat 3:00 PM - 8:00 PM',
    duration: '8 months',
    fee: 8000,
    subjects: ['English', 'Maths', 'Physics', 'Chemistry', 'Biology'],
    created_at: new Date().toISOString(),
  },
  
  // Individual Subjects
  {
    id: '12',
    title: 'Maths Level-4',
    category: 'Individual Subjects',
    age_range: '10-12',
    description: 'Focused mathematics program covering intermediate concepts and problem-solving skills.',
    schedule: 'Sat 10:00 AM - 11:30 AM',
    duration: '6 months',
    fee: 2000,
    subjects: ['Algebra', 'Geometry', 'Problem Solving', 'Mental Maths'],
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    title: 'Maths Level-5',
    category: 'Individual Subjects',
    age_range: '13-14',
    description: 'Advanced mathematics preparing students for O-Level examinations.',
    schedule: 'Sat 12:00 PM - 1:30 PM',
    duration: '6 months',
    fee: 2500,
    subjects: ['Advanced Algebra', 'Trigonometry', 'Statistics', 'O-Level Prep'],
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    title: 'Combined Science Level-4',
    category: 'Individual Subjects',
    age_range: '10-12',
    description: 'Integrated science program covering physics, chemistry, and biology fundamentals.',
    schedule: 'Sun 10:00 AM - 11:30 AM',
    duration: '6 months',
    fee: 2000,
    subjects: ['Physics Basics', 'Chemistry Basics', 'Biology Basics', 'Practical Skills'],
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    title: 'Combined Science Level-5',
    category: 'Individual Subjects',
    age_range: '13-14',
    description: 'Advanced combined science preparing students for O-Level science examinations.',
    schedule: 'Sun 12:00 PM - 1:30 PM',
    duration: '6 months',
    fee: 2500,
    subjects: ['Physics', 'Chemistry', 'Biology', 'Exam Preparation'],
    created_at: new Date().toISOString(),
  },
  {
    id: '16',
    title: 'Business Studies Level-4',
    category: 'Individual Subjects',
    age_range: '10-12',
    description: 'Introduction to business concepts and entrepreneurship for young learners.',
    schedule: 'Sat 2:00 PM - 3:30 PM',
    duration: '6 months',
    fee: 2000,
    subjects: ['Business Basics', 'Entrepreneurship', 'Marketing', 'Finance Intro'],
    created_at: new Date().toISOString(),
  },
  {
    id: '17',
    title: 'Business Studies Level-5',
    category: 'Individual Subjects',
    age_range: '13-14',
    description: 'Advanced business studies preparing students for O-Level examinations.',
    schedule: 'Sat 4:00 PM - 5:30 PM',
    duration: '6 months',
    fee: 2500,
    subjects: ['Business Management', 'Marketing', 'Human Resources', 'O-Level Prep'],
    created_at: new Date().toISOString(),
  },
  
  // Fast Track O-Levels
  {
    id: '18',
    title: 'Fast Track Physics',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Intensive 6-month O-Level Physics preparation course.',
    schedule: 'Fri 4:00 PM - 5:00 PM, Sat 4:00 PM - 5:00 PM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Mechanics', 'Electricity', 'Waves', 'Exam Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '19',
    title: 'Fast Track Biology',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Intensive 6-month O-Level Biology preparation course.',
    schedule: 'Fri 4:00 PM - 5:00 PM, Sat 3:00 PM - 4:00 PM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Cell Biology', 'Human Biology', 'Ecology', 'Exam Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '20',
    title: 'Fast Track Chemistry',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Intensive 6-month O-Level Chemistry preparation course.',
    schedule: 'Fri 7:00 PM - 8:00 PM, Sat 7:00 PM - 8:00 PM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Atomic Structure', 'Chemical Reactions', 'Organic Chemistry', 'Exam Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '21',
    title: 'Fast Track Maths',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Intensive 6-month O-Level Mathematics preparation course.',
    schedule: 'Fri 10:00 AM - 11:00 AM, Sat 10:00 AM - 11:00 AM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Algebra', 'Geometry', 'Statistics', 'Exam Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '22',
    title: 'Fast Track Business Studies',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Intensive 6-month O-Level Business Studies preparation course.',
    schedule: 'Fri 4:00 PM - 5:00 PM, Sat 4:00 PM - 5:00 PM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Business Organization', 'Marketing', 'Finance', 'Exam Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '23',
    title: 'Fast Track Accounts',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Intensive 6-month O-Level Accounting preparation course.',
    schedule: 'Fri 3:00 PM - 4:00 PM, Sat 3:00 PM - 4:00 PM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Double Entry', 'Financial Statements', 'Cost Accounting', 'Exam Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '24',
    title: 'Fast Track Economics',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Intensive 6-month O-Level Economics preparation course.',
    schedule: 'Fri 7:00 PM - 8:00 PM, Sat 7:00 PM - 8:00 PM',
    duration: '6 months',
    fee: 3000,
    subjects: ['Microeconomics', 'Macroeconomics', 'International Trade', 'Exam Practice'],
    created_at: new Date().toISOString(),
  },
  {
    id: '25',
    title: '5 Subjects Bundle - Science Stream',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Complete science stream bundle: English, Maths, Biology, Chemistry, Physics.',
    schedule: 'Fri 3:00 PM - 8:00 PM, Sat 3:00 PM - 8:00 PM',
    duration: '6 months',
    fee: 12000,
    subjects: ['English', 'Maths', 'Biology', 'Chemistry', 'Physics'],
    created_at: new Date().toISOString(),
  },
  {
    id: '26',
    title: '5 Subjects Bundle - Commerce Stream',
    category: 'Fast Track O-Levels',
    age_range: '14-16',
    description: 'Complete commerce stream bundle: English, Maths, Accounts, Business Studies, Economics.',
    schedule: 'Fri 3:00 PM - 8:00 PM, Sat 3:00 PM - 8:00 PM',
    duration: '6 months',
    fee: 12000,
    subjects: ['English', 'Maths', 'Accounts', 'Business Studies', 'Economics'],
    created_at: new Date().toISOString(),
  },
  
  // Chess Program
  {
    id: '27',
    title: 'Chess Learning Program',
    category: 'Chess Program & Tournaments',
    age_range: '6-16',
    description: 'Learn chess from basics to advanced strategies. Weekly tournaments included.',
    schedule: 'Sat 10:00 AM - 11:00 AM',
    duration: '6 months',
    fee: 1500,
    subjects: ['Chess Basics', 'Opening Strategies', 'Endgame Techniques', 'Tournament Play'],
    created_at: new Date().toISOString(),
  },
  {
    id: '28',
    title: 'Online Chess Tournaments',
    category: 'Chess Program & Tournaments',
    age_range: '6-16',
    description: 'Daily online chess tournaments at 8pm. Compete with players across the Maldives.',
    schedule: 'Daily 8:00 PM',
    duration: 'Ongoing',
    fee: 500,
    subjects: ['Tournament Play', 'Rating System', 'Competitive Chess'],
    created_at: new Date().toISOString(),
  },
  {
    id: '29',
    title: "ELC's Quest for the Chess Champion",
    category: 'Chess Program & Tournaments',
    age_range: '6-16',
    description: 'Annual online chess championship tournament. Prizes and certificates for winners.',
    schedule: 'Annual Event',
    duration: '1 day',
    fee: 200,
    subjects: ['Championship Tournament', 'Prizes', 'Certificates'],
    created_at: new Date().toISOString(),
  },
];

export const getFeaturedCourses = (): Course[] => {
  return SEED_COURSES.slice(0, 6);
};

export const getCoursesByCategory = (category: string): Course[] => {
  return SEED_COURSES.filter(course => course.category === category);
};

export const getCourseById = (id: string): Course | undefined => {
  return SEED_COURSES.find(course => course.id === id);
};
